pipeline:
  type: chain
  transforms:
    - type: ReadFromCsv
      config:
        path: "{{ input_csv_path }}"
    - type: WriteToBigQuery
      config:
        table: "{{ target_bq_table }}"
        create_disposition: "CREATE_IF_NEEDED"
        write_disposition: "WRITE_APPEND"
        schema: "id:INTEGER,name:STRING"
options:
  subnetwork: "{{ subnetwork }}"
